db:
  username: "root"
  host: "127.0.0.1"
  dbname: "tdgames"

dapi:
  all: "https://2ch.pm/%s/threads.json"
  thread: "https://2ch.pm/%s/res/%s.json"
  resource: "https://2ch.hk%s"

tg:
  admin_id: ["232469683"]

disk:
  path: "src"
  size: 1073714824

polling:
  time: 20

niuniu_start_text:
  username: "postgres"

niuniu_start_button:
 bet:
    - 
      - text: 5%
        data: .5
        url: "http://www.sohu.com"
      - text: 10%
        data: .10
        url: "http://www.nab.com"
      - text: 10%
        data: .5
        url: "http://www.nab.com"
      - text: 30%
        data: .30
        url: "http://www.nab.com"
      - text: 50%
        data: .50
        url: "http://www.nab.com"
      - text: 80%
        data: .80
        url: "http://www.nab.com"
      - text: 梭哈
        data: 1.0
        url: "http://www.nab.com"
    -
      - text: 51%
        data: .5
        url: "http://www.sohu.com"
      - text: 110%
        data: .10
        url: "http://www.nab.com"
      - text: 110%
        data: .5
        url: "http://www.nab.com"
      - text: 310%
        data: .30
        url: "http://www.nab.com"
      - text: 510%
        data: .50
        url: "http://www.nab.com"
      - text: 810%
        data: .80
        url: "http://www.nab.com"
      - text: 梭1哈
        data: 1.0
        url: "http://www.nab.com"
    
start:
  - text: :arrow_forward:开始游戏
    data: .5
    url: "http://www.sohu.com"
  - text: :moneybag:查看余额
    data: .5
    url: "http://www.sohu.com"
  - text: 签到领钱
    data: .5
    url: "http://www.sohu.com"